### ISSUE TITLE
Parameters missing from instruction table

### ISSUE THREAD

**Issue by j4james** [catseye/Funge-98#3]
In the _Instruction Quick Reference_ table, both the _Quit_ instruction and the _East-West If_ instruction are missing their input parameter in the _Before_ column (`r` for the former and `b` for the latter).

I suspect this data was lost in the conversion from HTML to markdown because it was certainly present in older versions of the documentation.

**Comment by cpressey** [comment]
Hmm, that is Worrisome™, because I used pandoc to convert all my languages' specs from HTML to Markdown, and if it missed this, I wonder what else it missed.

Otoh, from the history, it does look like I had to massage the output significantly, so maybe I manually missed this one.

I wrote a little script to extract the textual content from either HTML or Markdown: https://github.com/catseye/Dipple/commit/462c69df0071cb6c1afd91629e377e825d5f660a and doing this to both the MD spec and the original HTML spec (in https://github.com/catseye/Funge-98/commit/8642c2aa1a01cfd4c1dce737e8a186ea48e6c47e) and at a glance it does show some differences.

I have a years-long Befunge Backlog that I'll start working on this year, and I'll address this issue as part of it.  But if you would like to help speed the process along, feel free to put together a PR.

**Comment by cpressey** [comment]
I looked at the diff more closely and it does seem to have been a manual mistake rather than something pandoc got wrong.  I have made the change to restore them here:

https://bitbucket.org/catseye/funge-98/commits/e0844114cbe9e5160618f3bca023326455d9dd44

but due to a bug in hg-git I am currently unable to mirror some (maybe most) of my repos on GitHub:

https://bitbucket.org/durin42/hg-git/issues/181/git-mapfile-is-sometimes-completely

which unfortunately includes this repo.  Stay tuned for updates, I guess.

**Comment by j4james** [comment]
Thanks for the update. I have a slight preference for the GitHub version, partly for aesthetic reasons, but also because some of the images on Bitbucket don't work. But that seems less crucial, though, so will probably update my links to point there for now.

**Comment by cpressey** [comment]
I slightly prefer Github overall too and I'm not too surprised images are broken on Bitbucket.  The problems with the hg-git bridge have not been solved, but I've found a workaround (for every repo I've needed to sync so far, but maybe not for all of them.)  So, this repo has been updated with these changes, and I'll close these issues.  Thanks for reporting!
